### ISSUE TITLE
SendBuilder does not create valid sender

### ISSUE THREAD

**Issue by revilo196** [sp4ghet/ndi-rs#7]
Using default Send creation works fine 
``` rust
  let send = ndi::Send::new().expect("msg");
   println!("{}", send.get_source().get_name());
```
Returns: `MYCOMPUTER (send)` as expected

But when using SenderBuilder:
``` rust
   let send = ndi::SendBuilder::new().ndi_name("MyVideo".to_string()).clock_video(true).build().expect("Failed to create send");
   println!("{}", send.get_source().get_name());
```
Returns `MYCOMPUTER (�V��V)` and the Sender is not visible.

Looks like SenderBuilder.build() passes a ptr to a temporary cstr, that gets invalid before creattion

**Comment by sp4ghet** [comment]
merged the PR!
